# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\td_training\activities\research\Farm StandAlone\farm-standalone.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FarmStandAlone(object):
    def setupUi(self, FarmStandAlone):
        FarmStandAlone.setObjectName(_fromUtf8("FarmStandAlone"))
        FarmStandAlone.resize(594, 415)
        FarmStandAlone.setFrameShape(QtGui.QFrame.StyledPanel)
        FarmStandAlone.setFrameShadow(QtGui.QFrame.Raised)
        self.tabWidget = QtGui.QTabWidget(FarmStandAlone)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 571, 341))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_maya = QtGui.QWidget()
        self.tab_maya.setObjectName(_fromUtf8("tab_maya"))
        self.label_log_maya = QtGui.QLabel(self.tab_maya)
        self.label_log_maya.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_log_maya.setObjectName(_fromUtf8("label_log_maya"))
        self.label_framedash_maya = QtGui.QLabel(self.tab_maya)
        self.label_framedash_maya.setGeometry(QtCore.QRect(160, 110, 21, 16))
        self.label_framedash_maya.setObjectName(_fromUtf8("label_framedash_maya"))
        self.label_jobtitle_maya = QtGui.QLabel(self.tab_maya)
        self.label_jobtitle_maya.setGeometry(QtCore.QRect(10, 20, 46, 16))
        self.label_jobtitle_maya.setObjectName(_fromUtf8("label_jobtitle_maya"))
        self.sb_eframe_maya = QtGui.QSpinBox(self.tab_maya)
        self.sb_eframe_maya.setGeometry(QtCore.QRect(180, 110, 42, 22))
        self.sb_eframe_maya.setObjectName(_fromUtf8("sb_eframe_maya"))
        self.label_outdir_maya = QtGui.QLabel(self.tab_maya)
        self.label_outdir_maya.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.label_outdir_maya.setObjectName(_fromUtf8("label_outdir_maya"))
        self.le_jobtitle_maya = QtGui.QLineEdit(self.tab_maya)
        self.le_jobtitle_maya.setGeometry(QtCore.QRect(110, 20, 421, 20))
        self.le_jobtitle_maya.setObjectName(_fromUtf8("le_jobtitle_maya"))
        self.sb_sframe_maya = QtGui.QSpinBox(self.tab_maya)
        self.sb_sframe_maya.setGeometry(QtCore.QRect(110, 110, 42, 22))
        self.sb_sframe_maya.setObjectName(_fromUtf8("sb_sframe_maya"))
        self.label_frames_maya = QtGui.QLabel(self.tab_maya)
        self.label_frames_maya.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_frames_maya.setObjectName(_fromUtf8("label_frames_maya"))
        self.button_send_maya = QtGui.QPushButton(self.tab_maya)
        self.button_send_maya.setGeometry(QtCore.QRect(420, 280, 111, 23))
        self.button_send_maya.setObjectName(_fromUtf8("button_send_maya"))
        self.le_outdir_maya = QtGui.QLineEdit(self.tab_maya)
        self.le_outdir_maya.setGeometry(QtCore.QRect(110, 170, 421, 20))
        self.le_outdir_maya.setObjectName(_fromUtf8("le_outdir_maya"))
        self.label_mayafile = QtGui.QLabel(self.tab_maya)
        self.label_mayafile.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_mayafile.setObjectName(_fromUtf8("label_mayafile"))
        self.le_log_maya = QtGui.QLineEdit(self.tab_maya)
        self.le_log_maya.setGeometry(QtCore.QRect(110, 80, 421, 20))
        self.le_log_maya.setObjectName(_fromUtf8("le_log_maya"))
        self.sb_enablebatch_maya = QtGui.QSpinBox(self.tab_maya)
        self.sb_enablebatch_maya.setGeometry(QtCore.QRect(490, 110, 42, 22))
        self.sb_enablebatch_maya.setObjectName(_fromUtf8("sb_enablebatch_maya"))
        self.le_mayafile = QtGui.QLineEdit(self.tab_maya)
        self.le_mayafile.setGeometry(QtCore.QRect(110, 50, 421, 20))
        self.le_mayafile.setObjectName(_fromUtf8("le_mayafile"))
        self.cb_enablebatch_maya = QtGui.QCheckBox(self.tab_maya)
        self.cb_enablebatch_maya.setGeometry(QtCore.QRect(350, 110, 131, 17))
        self.cb_enablebatch_maya.setObjectName(_fromUtf8("cb_enablebatch_maya"))
        self.cb_renderer_maya = QtGui.QComboBox(self.tab_maya)
        self.cb_renderer_maya.setGeometry(QtCore.QRect(110, 140, 141, 22))
        self.cb_renderer_maya.setObjectName(_fromUtf8("cb_renderer_maya"))
        self.cb_renderer_maya.addItem(_fromUtf8(""))
        self.cb_renderer_maya.addItem(_fromUtf8(""))
        self.cb_renderer_maya.addItem(_fromUtf8(""))
        self.label_cpus_maya = QtGui.QLabel(self.tab_maya)
        self.label_cpus_maya.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_cpus_maya.setObjectName(_fromUtf8("label_cpus_maya"))
        self.label_renderer_maya = QtGui.QLabel(self.tab_maya)
        self.label_renderer_maya.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_renderer_maya.setObjectName(_fromUtf8("label_renderer_maya"))
        self.te_cpus_maya = QtGui.QTextEdit(self.tab_maya)
        self.te_cpus_maya.setGeometry(QtCore.QRect(110, 200, 421, 71))
        self.te_cpus_maya.setObjectName(_fromUtf8("te_cpus_maya"))
        self.tabWidget.addTab(self.tab_maya, _fromUtf8(""))
        self.tab_max = QtGui.QWidget()
        self.tab_max.setObjectName(_fromUtf8("tab_max"))
        self.label_jobtitle_max = QtGui.QLabel(self.tab_max)
        self.label_jobtitle_max.setGeometry(QtCore.QRect(10, 20, 46, 16))
        self.label_jobtitle_max.setObjectName(_fromUtf8("label_jobtitle_max"))
        self.le_jobtitle_max = QtGui.QLineEdit(self.tab_max)
        self.le_jobtitle_max.setGeometry(QtCore.QRect(110, 20, 421, 20))
        self.le_jobtitle_max.setObjectName(_fromUtf8("le_jobtitle_max"))
        self.label_maxfile = QtGui.QLabel(self.tab_max)
        self.label_maxfile.setGeometry(QtCore.QRect(10, 50, 46, 16))
        self.label_maxfile.setObjectName(_fromUtf8("label_maxfile"))
        self.le_maxfile = QtGui.QLineEdit(self.tab_max)
        self.le_maxfile.setGeometry(QtCore.QRect(110, 50, 421, 20))
        self.le_maxfile.setObjectName(_fromUtf8("le_maxfile"))
        self.label_outdir_max = QtGui.QLabel(self.tab_max)
        self.label_outdir_max.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_outdir_max.setObjectName(_fromUtf8("label_outdir_max"))
        self.le_outdir_max = QtGui.QLineEdit(self.tab_max)
        self.le_outdir_max.setGeometry(QtCore.QRect(110, 80, 421, 20))
        self.le_outdir_max.setObjectName(_fromUtf8("le_outdir_max"))
        self.sb_sframe_max = QtGui.QSpinBox(self.tab_max)
        self.sb_sframe_max.setGeometry(QtCore.QRect(110, 110, 42, 22))
        self.sb_sframe_max.setObjectName(_fromUtf8("sb_sframe_max"))
        self.sb_eframe_max = QtGui.QSpinBox(self.tab_max)
        self.sb_eframe_max.setGeometry(QtCore.QRect(180, 110, 42, 22))
        self.sb_eframe_max.setObjectName(_fromUtf8("sb_eframe_max"))
        self.label_frames_max = QtGui.QLabel(self.tab_max)
        self.label_frames_max.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_frames_max.setObjectName(_fromUtf8("label_frames_max"))
        self.label_framedash_max = QtGui.QLabel(self.tab_max)
        self.label_framedash_max.setGeometry(QtCore.QRect(160, 110, 21, 16))
        self.label_framedash_max.setObjectName(_fromUtf8("label_framedash_max"))
        self.label_cpus_max = QtGui.QLabel(self.tab_max)
        self.label_cpus_max.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_cpus_max.setObjectName(_fromUtf8("label_cpus_max"))
        self.sb_enablebatch_max = QtGui.QSpinBox(self.tab_max)
        self.sb_enablebatch_max.setGeometry(QtCore.QRect(490, 110, 42, 22))
        self.sb_enablebatch_max.setObjectName(_fromUtf8("sb_enablebatch_max"))
        self.cb_enablebatch_max = QtGui.QCheckBox(self.tab_max)
        self.cb_enablebatch_max.setGeometry(QtCore.QRect(350, 110, 131, 17))
        self.cb_enablebatch_max.setObjectName(_fromUtf8("cb_enablebatch_max"))
        self.te_cpus_max = QtGui.QTextEdit(self.tab_max)
        self.te_cpus_max.setGeometry(QtCore.QRect(110, 200, 421, 71))
        self.te_cpus_max.setObjectName(_fromUtf8("te_cpus_max"))
        self.label_maxtime_max = QtGui.QLabel(self.tab_max)
        self.label_maxtime_max.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_maxtime_max.setObjectName(_fromUtf8("label_maxtime_max"))
        self.le_maxtime_max = QtGui.QLineEdit(self.tab_max)
        self.le_maxtime_max.setGeometry(QtCore.QRect(110, 140, 131, 20))
        self.le_maxtime_max.setObjectName(_fromUtf8("le_maxtime_max"))
        self.button_send_max = QtGui.QPushButton(self.tab_max)
        self.button_send_max.setGeometry(QtCore.QRect(420, 280, 111, 23))
        self.button_send_max.setObjectName(_fromUtf8("button_send_max"))
        self.le_logdir_max = QtGui.QLineEdit(self.tab_max)
        self.le_logdir_max.setGeometry(QtCore.QRect(110, 170, 421, 20))
        self.le_logdir_max.setObjectName(_fromUtf8("le_logdir_max"))
        self.label_log_max = QtGui.QLabel(self.tab_max)
        self.label_log_max.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_log_max.setObjectName(_fromUtf8("label_log_max"))
        self.tabWidget.addTab(self.tab_max, _fromUtf8(""))
        self.tab_blend = QtGui.QWidget()
        self.tab_blend.setObjectName(_fromUtf8("tab_blend"))
        self.le_jobtitle_blender = QtGui.QLineEdit(self.tab_blend)
        self.le_jobtitle_blender.setGeometry(QtCore.QRect(110, 20, 421, 20))
        self.le_jobtitle_blender.setObjectName(_fromUtf8("le_jobtitle_blender"))
        self.label_jobtitle_blender = QtGui.QLabel(self.tab_blend)
        self.label_jobtitle_blender.setGeometry(QtCore.QRect(10, 20, 46, 16))
        self.label_jobtitle_blender.setObjectName(_fromUtf8("label_jobtitle_blender"))
        self.label_log_blender = QtGui.QLabel(self.tab_blend)
        self.label_log_blender.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_log_blender.setObjectName(_fromUtf8("label_log_blender"))
        self.le_log_blender = QtGui.QLineEdit(self.tab_blend)
        self.le_log_blender.setGeometry(QtCore.QRect(110, 80, 421, 20))
        self.le_log_blender.setObjectName(_fromUtf8("le_log_blender"))
        self.label_frames = QtGui.QLabel(self.tab_blend)
        self.label_frames.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_frames.setObjectName(_fromUtf8("label_frames"))
        self.label_renderengine_blender = QtGui.QLabel(self.tab_blend)
        self.label_renderengine_blender.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_renderengine_blender.setObjectName(_fromUtf8("label_renderengine_blender"))
        self.cb_renderengine_blender = QtGui.QComboBox(self.tab_blend)
        self.cb_renderengine_blender.setGeometry(QtCore.QRect(110, 140, 141, 22))
        self.cb_renderengine_blender.setObjectName(_fromUtf8("cb_renderengine_blender"))
        self.cb_renderengine_blender.addItem(_fromUtf8(""))
        self.cb_renderengine_blender.addItem(_fromUtf8(""))
        self.cb_renderengine_blender.addItem(_fromUtf8(""))
        self.cb_enableframe_blender = QtGui.QCheckBox(self.tab_blend)
        self.cb_enableframe_blender.setGeometry(QtCore.QRect(350, 110, 131, 17))
        self.cb_enableframe_blender.setObjectName(_fromUtf8("cb_enableframe_blender"))
        self.sb_enableframe_blender = QtGui.QSpinBox(self.tab_blend)
        self.sb_enableframe_blender.setGeometry(QtCore.QRect(490, 110, 42, 22))
        self.sb_enableframe_blender.setObjectName(_fromUtf8("sb_enableframe_blender"))
        self.le_blendfile = QtGui.QLineEdit(self.tab_blend)
        self.le_blendfile.setGeometry(QtCore.QRect(110, 50, 421, 20))
        self.le_blendfile.setObjectName(_fromUtf8("le_blendfile"))
        self.label_blendfile = QtGui.QLabel(self.tab_blend)
        self.label_blendfile.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_blendfile.setObjectName(_fromUtf8("label_blendfile"))
        self.button_send_blender = QtGui.QPushButton(self.tab_blend)
        self.button_send_blender.setGeometry(QtCore.QRect(420, 280, 111, 23))
        self.button_send_blender.setObjectName(_fromUtf8("button_send_blender"))
        self.sb_sframe_blender = QtGui.QSpinBox(self.tab_blend)
        self.sb_sframe_blender.setGeometry(QtCore.QRect(110, 110, 42, 22))
        self.sb_sframe_blender.setObjectName(_fromUtf8("sb_sframe_blender"))
        self.sb_eframe_blender = QtGui.QSpinBox(self.tab_blend)
        self.sb_eframe_blender.setGeometry(QtCore.QRect(180, 110, 42, 22))
        self.sb_eframe_blender.setObjectName(_fromUtf8("sb_eframe_blender"))
        self.label_framedash_blender = QtGui.QLabel(self.tab_blend)
        self.label_framedash_blender.setGeometry(QtCore.QRect(160, 110, 21, 16))
        self.label_framedash_blender.setObjectName(_fromUtf8("label_framedash_blender"))
        self.label_cpus_blender = QtGui.QLabel(self.tab_blend)
        self.label_cpus_blender.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_cpus_blender.setObjectName(_fromUtf8("label_cpus_blender"))
        self.te_cpus_blender = QtGui.QTextEdit(self.tab_blend)
        self.te_cpus_blender.setGeometry(QtCore.QRect(110, 200, 421, 71))
        self.te_cpus_blender.setObjectName(_fromUtf8("te_cpus_blender"))
        self.le_outdir_blender = QtGui.QLineEdit(self.tab_blend)
        self.le_outdir_blender.setGeometry(QtCore.QRect(110, 170, 421, 20))
        self.le_outdir_blender.setObjectName(_fromUtf8("le_outdir_blender"))
        self.label_outdir_blender = QtGui.QLabel(self.tab_blend)
        self.label_outdir_blender.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.label_outdir_blender.setObjectName(_fromUtf8("label_outdir_blender"))
        self.tabWidget.addTab(self.tab_blend, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_scenepath_ae = QtGui.QLabel(self.tab)
        self.label_scenepath_ae.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_scenepath_ae.setObjectName(_fromUtf8("label_scenepath_ae"))
        self.label_framedash_ae = QtGui.QLabel(self.tab)
        self.label_framedash_ae.setGeometry(QtCore.QRect(160, 110, 21, 16))
        self.label_framedash_ae.setObjectName(_fromUtf8("label_framedash_ae"))
        self.label_frames_ae = QtGui.QLabel(self.tab)
        self.label_frames_ae.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_frames_ae.setObjectName(_fromUtf8("label_frames_ae"))
        self.sb_eframe_ae = QtGui.QSpinBox(self.tab)
        self.sb_eframe_ae.setGeometry(QtCore.QRect(180, 110, 42, 22))
        self.sb_eframe_ae.setObjectName(_fromUtf8("sb_eframe_ae"))
        self.cb_enablebatch_ae = QtGui.QCheckBox(self.tab)
        self.cb_enablebatch_ae.setGeometry(QtCore.QRect(350, 110, 131, 17))
        self.cb_enablebatch_ae.setObjectName(_fromUtf8("cb_enablebatch_ae"))
        self.button_send_ae = QtGui.QPushButton(self.tab)
        self.button_send_ae.setGeometry(QtCore.QRect(420, 280, 111, 23))
        self.button_send_ae.setObjectName(_fromUtf8("button_send_ae"))
        self.le_scenepath_ae = QtGui.QLineEdit(self.tab)
        self.le_scenepath_ae.setGeometry(QtCore.QRect(110, 50, 421, 20))
        self.le_scenepath_ae.setObjectName(_fromUtf8("le_scenepath_ae"))
        self.label_cpus_ae = QtGui.QLabel(self.tab)
        self.label_cpus_ae.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_cpus_ae.setObjectName(_fromUtf8("label_cpus_ae"))
        self.label_jobtitle_ae = QtGui.QLabel(self.tab)
        self.label_jobtitle_ae.setGeometry(QtCore.QRect(10, 20, 46, 16))
        self.label_jobtitle_ae.setObjectName(_fromUtf8("label_jobtitle_ae"))
        self.le_jobtitle_ae = QtGui.QLineEdit(self.tab)
        self.le_jobtitle_ae.setGeometry(QtCore.QRect(110, 20, 421, 20))
        self.le_jobtitle_ae.setObjectName(_fromUtf8("le_jobtitle_ae"))
        self.sb_enablebatch_ae = QtGui.QSpinBox(self.tab)
        self.sb_enablebatch_ae.setGeometry(QtCore.QRect(490, 110, 42, 22))
        self.sb_enablebatch_ae.setObjectName(_fromUtf8("sb_enablebatch_ae"))
        self.label_maxtime_ae = QtGui.QLabel(self.tab)
        self.label_maxtime_ae.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_maxtime_ae.setObjectName(_fromUtf8("label_maxtime_ae"))
        self.le_outdir_ae = QtGui.QLineEdit(self.tab)
        self.le_outdir_ae.setGeometry(QtCore.QRect(110, 80, 421, 20))
        self.le_outdir_ae.setObjectName(_fromUtf8("le_outdir_ae"))
        self.label_outdir_ae = QtGui.QLabel(self.tab)
        self.label_outdir_ae.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_outdir_ae.setObjectName(_fromUtf8("label_outdir_ae"))
        self.le_maxtime_ae = QtGui.QLineEdit(self.tab)
        self.le_maxtime_ae.setGeometry(QtCore.QRect(110, 170, 131, 20))
        self.le_maxtime_ae.setObjectName(_fromUtf8("le_maxtime_ae"))
        self.sb_sframe_ae = QtGui.QSpinBox(self.tab)
        self.sb_sframe_ae.setGeometry(QtCore.QRect(110, 110, 42, 22))
        self.sb_sframe_ae.setObjectName(_fromUtf8("sb_sframe_ae"))
        self.te_cpus_ae = QtGui.QTextEdit(self.tab)
        self.te_cpus_ae.setGeometry(QtCore.QRect(110, 200, 421, 71))
        self.te_cpus_ae.setObjectName(_fromUtf8("te_cpus_ae"))
        self.label_compname_ae = QtGui.QLabel(self.tab)
        self.label_compname_ae.setGeometry(QtCore.QRect(260, 170, 71, 16))
        self.label_compname_ae.setObjectName(_fromUtf8("label_compname_ae"))
        self.le_compname_ae = QtGui.QLineEdit(self.tab)
        self.le_compname_ae.setGeometry(QtCore.QRect(330, 170, 201, 20))
        self.le_compname_ae.setObjectName(_fromUtf8("le_compname_ae"))
        self.label_version_ae = QtGui.QLabel(self.tab)
        self.label_version_ae.setGeometry(QtCore.QRect(230, 110, 71, 16))
        self.label_version_ae.setObjectName(_fromUtf8("label_version_ae"))
        self.cb_version_ae = QtGui.QComboBox(self.tab)
        self.cb_version_ae.setGeometry(QtCore.QRect(290, 110, 51, 22))
        self.cb_version_ae.setObjectName(_fromUtf8("cb_version_ae"))
        self.cb_version_ae.addItem(_fromUtf8(""))
        self.cb_version_ae.addItem(_fromUtf8(""))
        self.cb_version_ae.addItem(_fromUtf8(""))
        self.le_logdir_ae = QtGui.QLineEdit(self.tab)
        self.le_logdir_ae.setGeometry(QtCore.QRect(110, 140, 421, 20))
        self.le_logdir_ae.setObjectName(_fromUtf8("le_logdir_ae"))
        self.label_logdir_ae = QtGui.QLabel(self.tab)
        self.label_logdir_ae.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_logdir_ae.setObjectName(_fromUtf8("label_logdir_ae"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.label = QtGui.QLabel(FarmStandAlone)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 21))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(FarmStandAlone)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(FarmStandAlone)

    def retranslateUi(self, FarmStandAlone):
        FarmStandAlone.setWindowTitle(_translate("FarmStandAlone", "Farm Stand Alone", None))
        self.label_log_maya.setText(_translate("FarmStandAlone", "Log Directory", None))
        self.label_framedash_maya.setText(_translate("FarmStandAlone", "-", None))
        self.label_jobtitle_maya.setText(_translate("FarmStandAlone", "Job Title", None))
        self.label_outdir_maya.setText(_translate("FarmStandAlone", "Output Directory", None))
        self.label_frames_maya.setText(_translate("FarmStandAlone", "Frames", None))
        self.button_send_maya.setText(_translate("FarmStandAlone", "Send", None))
        self.label_mayafile.setText(_translate("FarmStandAlone", "Maya File", None))
        self.cb_enablebatch_maya.setText(_translate("FarmStandAlone", "Enable Batch Framing", None))
        self.cb_renderer_maya.setItemText(0, _translate("FarmStandAlone", "Software", None))
        self.cb_renderer_maya.setItemText(1, _translate("FarmStandAlone", "Hardware", None))
        self.cb_renderer_maya.setItemText(2, _translate("FarmStandAlone", "Mental Ray", None))
        self.label_cpus_maya.setText(_translate("FarmStandAlone", "Cpus", None))
        self.label_renderer_maya.setText(_translate("FarmStandAlone", "Renderer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_maya), _translate("FarmStandAlone", "Maya", None))
        self.label_jobtitle_max.setText(_translate("FarmStandAlone", "Job Title", None))
        self.label_maxfile.setText(_translate("FarmStandAlone", "Max File", None))
        self.label_outdir_max.setText(_translate("FarmStandAlone", "Output Directory", None))
        self.label_frames_max.setText(_translate("FarmStandAlone", "Frames", None))
        self.label_framedash_max.setText(_translate("FarmStandAlone", "-", None))
        self.label_cpus_max.setText(_translate("FarmStandAlone", "Cpus", None))
        self.cb_enablebatch_max.setText(_translate("FarmStandAlone", "Enable Batch Framing", None))
        self.label_maxtime_max.setText(_translate("FarmStandAlone", "Max Time", None))
        self.button_send_max.setText(_translate("FarmStandAlone", "Send", None))
        self.label_log_max.setText(_translate("FarmStandAlone", "Log Directory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_max), _translate("FarmStandAlone", "3ds Max", None))
        self.label_jobtitle_blender.setText(_translate("FarmStandAlone", "Job Title", None))
        self.label_log_blender.setText(_translate("FarmStandAlone", "Log Directory", None))
        self.label_frames.setText(_translate("FarmStandAlone", "Frames", None))
        self.label_renderengine_blender.setText(_translate("FarmStandAlone", "Render Engine", None))
        self.cb_renderengine_blender.setItemText(0, _translate("FarmStandAlone", "Blender Render", None))
        self.cb_renderengine_blender.setItemText(1, _translate("FarmStandAlone", "Cycles Render", None))
        self.cb_renderengine_blender.setItemText(2, _translate("FarmStandAlone", "Blender Game ", None))
        self.cb_enableframe_blender.setText(_translate("FarmStandAlone", "Enable Batch Framing", None))
        self.label_blendfile.setText(_translate("FarmStandAlone", "Blend File", None))
        self.button_send_blender.setText(_translate("FarmStandAlone", "Send", None))
        self.label_framedash_blender.setText(_translate("FarmStandAlone", "-", None))
        self.label_cpus_blender.setText(_translate("FarmStandAlone", "Cpus", None))
        self.label_outdir_blender.setText(_translate("FarmStandAlone", "Output Directory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_blend), _translate("FarmStandAlone", "Blender", None))
        self.label_scenepath_ae.setText(_translate("FarmStandAlone", "Scene Path", None))
        self.label_framedash_ae.setText(_translate("FarmStandAlone", "-", None))
        self.label_frames_ae.setText(_translate("FarmStandAlone", "Frames", None))
        self.cb_enablebatch_ae.setText(_translate("FarmStandAlone", "Enable Batch Framing", None))
        self.button_send_ae.setText(_translate("FarmStandAlone", "Send", None))
        self.label_cpus_ae.setText(_translate("FarmStandAlone", "Cpus", None))
        self.label_jobtitle_ae.setText(_translate("FarmStandAlone", "Job Title", None))
        self.label_maxtime_ae.setText(_translate("FarmStandAlone", "Max Time", None))
        self.label_outdir_ae.setText(_translate("FarmStandAlone", "Output Directory", None))
        self.label_compname_ae.setText(_translate("FarmStandAlone", "Comp Name", None))
        self.label_version_ae.setText(_translate("FarmStandAlone", "AE Version", None))
        self.cb_version_ae.setItemText(0, _translate("FarmStandAlone", "CS5", None))
        self.cb_version_ae.setItemText(1, _translate("FarmStandAlone", "CS6", None))
        self.cb_version_ae.setItemText(2, _translate("FarmStandAlone", "CC", None))
        self.label_logdir_ae.setText(_translate("FarmStandAlone", "Log Directory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FarmStandAlone", "After Effects", None))
        self.label.setText(_translate("FarmStandAlone", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Farm Stand-Alone</span></p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FarmStandAlone = QtGui.QFrame()
    ui = Ui_FarmStandAlone()
    ui.setupUi(FarmStandAlone)
    FarmStandAlone.show()
    sys.exit(app.exec_())

